apiVersion: 1

datasources:
  - name: Prometheus
    uid: PROMETHEUS
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    uid: LOKI
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: TEMPO
          matcherRegex: '"traceId"\s*:\s*"([0-9a-fA-F]{32})"'
          name: TraceID
          url: "$${__value.raw}"

  - name: Tempo
    uid: TEMPO
    type: tempo
    access: proxy
    url: http://tempo-grafana-proxy:3200
