global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
  - job_name: "gateway"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["gateway:4000"]
  - job_name: "balance"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["balance:9102"]
  - job_name: "player"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["player:9103"]
  - job_name: "game"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["game:9105"]
  - job_name: "event"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["event:9104"]
  - job_name: "notify"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["notify:9105"]
